EmployeeDAO.getAllEmployeesBySalary=from EmployeeEntity k where k.salary>=?1
EmployeeDAO.getDeptCodesAndCountOfEmployee=select count(k),k.departmentCode from EmployeeEntity k group by k.departmentCode

#interfaceName.methodName is used a key best practise