#input=file:/Users/sharmilee.jalal/eclipse-workspace/SpringBatch4/Demo_3.1A_SpringBoot_WithSpring_Batch_JavaConfig/src/main/resources/com/accenture/lkm/resources/employee.csv
input=classpath:employee.csv
spring.main.allow-bean-definition-overriding=true
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
spring.datasource.url=jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto = update
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
#debug=true