#input=file:/Users/sharmilee.jalal/eclipse-workspace/SpringBatch4/Demo_3.1_SpringBoot_WithSpring_Batch/src/main/resources/com/accenture/lkm/resources/employee.csv
input=classpath:employee.csv
my_cst_db_driver=com.mysql.cj.jdbc.Driver
my_cst_db_url=jdbc:mysql://localhost:3306/spring_batch_boot_demos
my_cst_user=root
my_cst_password=root