server.port = 7093


resilience4j.circuitbreaker.instances.jasKeyCompute.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.circuitbreaker.instances.jasKeyCompute.failureRateThreshold=50
resilience4j.circuitbreaker.instances.jasKeyCompute.minimumNumberOfCalls=6
resilience4j.circuitbreaker.instances.jasKeyCompute.waitDurationInOpenState=60s

resilience4j.circuitbreaker.instances.jasKeyCompute.permittedNumberOfCallsInHalfOpenState=4

resilience4j.circuitbreaker.instances.jasKeyCompute.slidingWindowType=COUNT_BASED
