cst_db_driver=org.sqlite.JDBC
cst_db_url=jdbc:sqlite:repository.sqlite
cst_user=""
cst_password=""

my_cst_db_driver=com.mysql.cj.jdbc.Driver
my_cst_db_url=jdbc:mysql://localhost:3306/spring_batch_demos
my_cst_user=root
my_cst_password=root